on: pull_request
name: Lint npm packages on pull request
jobs:
  npmLint:
    name: npm lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Run npm install
        run: npm ci --ignore-scripts

      - name: Run test
        run: npm run test --workspaces --if-present
